[ADD] allow adding calendar links to time off calendar, default icals
verdigado/odoo-customize pull request #26
Opened 2023-09-25 12:41 UTC by hbrunn

in https://github.com/OCA/server-backend/pull/231 habe ich ein auto-flag hinzugefügt, mit dem ein Kalender fur alle user aktiviert wird (sie können das von Hand wieder deaktivieren).

Hier gibt es ein flag um bestimmte Kalender im Leave-Kalender anzuzeigen, die Links erscheinen dann unter der Legende.

Weiterhin definiere ich zwei Standardkalender die automatisch aktiviert sind und in der Kalender-Ansicht angezeigt werden.

Diskussion:

1. 'Mein Team' habe ich jetzt definiert als 'In meiner Abteilung', das muss ggf noch verändert werden
2. Statt nur dem Link vielleicht besser wenn ein Click die URL in die Zwischenablage kopiert und das in einem Popup sagt?

2023-11-17 15:06 UTC, albig commented
Ich wollte das mal wieder ausprobieren, scheitere an folgender Fehlermeldung, die mich leider ratlos macht:

```
odoo15-web15-1    |   File "/mnt/extra-addons/server-backend/base_ical/models/base_ical.py", line 191, in _get_ical
odoo15-web15-1    |     event.add(field.vevent_field).value = self._format_ical_value(
odoo15-web15-1    |   File "/mnt/extra-addons/server-backend/base_ical/models/base_ical.py", line 199, in _format_ical_value
odoo15-web15-1    |     return pytz.utc.localize(value).astimezone(pytz.timezone(self.env.user.tz))
odoo15-web15-1    |   File "/usr/lib/python3/dist-packages/pytz/__init__.py", line 170, in timezone
odoo15-web15-1    |     if zone.upper() == 'UTC':
odoo15-web15-1    | AttributeError: 'bool' object has no attribute 'upper'
```

2023-11-20 06:03 UTC, hbrunn commented
das sieht aus wie ein Benutzer ohne gesetzte Zeitzone - das sollte bei Euch ohnehin default Europe/Berlin sein denke ich? (sowas könnte Teil der Defaults/Templates sein die wir ohnehin erstellen wollen)

2023-11-20 08:41 UTC, albig commented
Der Benutzer hat die richtige Zeitzone. Das passiert, wenn man den Modul `verdigado_attendance` upgraden will.

2023-11-20 09:32 UTC, hbrunn commented
gilt das auch fur den system-user (__system__)?

2023-11-20 09:40 UTC, hbrunn commented
habe ein Fallback für nicht konfigurierte Zeitzonen eingebaut. Aber falls der __system__ user keine Zeitzone hat sollte er die gesetzt bekommen, ansonsten läuft mancher Code in der falschen Zeitzone

2023-11-20 10:11 UTC, albig commented
Das war's tatsächlich. Der User `__system__` ist ja ausgeblendet und hatte keine Zeitzone.

Jetzt scheitert's hier:

```
odoo15-web15-1    |   File "/usr/lib/python3/dist-packages/vobject/base.py", line 1219, in backslashEscape
odoo15-web15-1    |     s = s.replace("\\", "\\\\").replace(";", "\;").replace(",", "\,")
odoo15-web15-1    | AttributeError: 'bool' object has no attribute 'replace'
odoo15-web15-1    |
odoo15-web15-1    | The above exception was the direct cause of the following exception:

odoo15-web15-1    |   File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 696, in _tag_root
odoo15-web15-1    |     raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo15-web15-1    | odoo.tools.convert.ParseError: while parsing /mnt/extra-addons/verdigado_attendance/data/base_ical.xml:16, somewhere inside
odoo15-web15-1    | <record id="ical_my_team_leaves" model="base.ical">
odoo15-web15-1    |         <field name="name">My team leaves</field>
odoo15-web15-1    |         <field name="model_id" ref="hr_holidays.model_hr_leave"/>
```
Das lief doch schon mal...?

2023-11-20 10:39 UTC, hbrunn commented
das ist abhängig von den bestehenden Daten, ich habe jetzt in den Ausdrücken für das name-Feld ein `or ''` zugefügt, das sollte diesen Fehler beheben

2023-11-20 12:29 UTC, albig commented
Danke, auch das läuft jetzt.

Jetzt möchte ich "My leaves" bearbeiten unter Technisches -> iCalendars. Das endet in einem JavaScript-Fehler.

```
web.assets_backend.min.js:2951 Uncaught (in promise) Error: NameError: name 'user' is not defined
    at PY_ensurepy (web.assets_backend.min.js:2951:65)
    at py.evaluate (web.assets_backend.min.js:3068:8)
    at py.evaluate (web.assets_backend.min.js:3080:25)
    at py.evaluate (web.assets_backend.min.js:3075:111)
    at py.evaluate (web.assets_backend.min.js:3077:99)
    at py.eval (web.assets_backend.min.js:3082:284)
    at web.assets_backend.min.js:3881:136
    at _.each._.forEach (web.assets_common.min.js:153:404)
    at _.<computed> [as each] (web.assets_common.min.js:218:498)
    at eval_domains (web.assets_backend.min.js:3880:265)
```

Unter "Domain" steht nur "Diese Domain wird nicht unterstützt.".

2023-11-20 13:09 UTC, hbrunn commented
ah, deshalb habe ich in der ersten Version das domain-widget nicht verwendet. Das wieder zurück gebaut

2023-11-22 08:36 UTC, albig requested changes
Noch zwei Fragen bzw. Änderungswünsche.

2023-11-22 08:36 UTC, albig commented on verdigado_attendance/data/base_ical.xml
> +        <field name="domain">
Wie müsste die Domain lauten, wenn ich
* keine Departments verwende
* alle MAs des Unternehmens

angezeigt werden sollen?

2023-11-22 08:36 UTC, albig commented on verdigado_attendance/data/base_ical.xml
> +        <field name="expression_summary">record.name or ''</field>
Bei "My Team Leaves" bitte nur den Namen, keinen Grund oder ähnliches.

Es scheint zu funktionieren:
`<field name="expression_summary">record.employee_id.name or ''</field>`

Kann man den Abwesenheits-Typ hier ermitteln? Also dass dann z.B. steht "Alexander Bigga: Urlaub", wenn der Abwesenheits-Typ "Urlaub" (original: "Bezahlte Abwesenheit") lautet?

2023-11-22 09:17 UTC, hbrunn commented on verdigado_attendance/data/base_ical.xml
> +        <field name="expression_summary">record.name or ''</field>
`'%s: %s' % (record.employee_id.name, record.holiday_status_id.name)`

2023-11-22 09:19 UTC, hbrunn commented on verdigado_attendance/data/base_ical.xml
> +        <field name="domain">
`[]` - dann wird es nur durch die record rules beschränkt. Wenn das bestehende record rules umgehen soll, muss ich etwas mehr tun, bisher läuft das alles mit den Rechten des Benutzers dem der Link gehört.

2023-11-22 09:37 UTC, albig commented on verdigado_attendance/data/base_ical.xml
> +        <field name="expression_summary">record.name or ''</field>
Super, wenn Du das noch hier änderst, dann merg ich das.

2023-11-22 11:18 UTC, hbrunn commented on verdigado_attendance/data/base_ical.xml
> +        <field name="expression_summary">record.name or ''</field>
domain im Teamkalender angepasst und die namen verändert

2023-11-27 12:51 UTC, albig approved these changes

2023-11-27 12:51 UTC, merged