[ADD] #3 hr_holidays: show hours with float_time widget, make numbers links
verdigado/odoo-customize pull request #4
Opened 2023-07-03 10:25 UTC by hbrunn

ich pushe schon einmal den UI-Teil weil absehbar ist dass ich die Korrektur der Odoo-Überstunden nicht bis zum Meeting fertig bekommen werde.

Sobald wir besprochen haben wie wir mit deployment, CI und checkers umgehen kann wohl ein Teil davon in bestehende OCA-Module überführt werden.

2023-07-31 15:26 UTC, hbrunn commented
@albig rebased nach dem merge mit vielen Reformatierungen. Jetzt laufen die Tests auch, schlagen aber fehl weil ich vergessen habe die dafür relevanten Dateien zu pushen. Kommt gleich in einem eigenen PR nach

2023-08-02 08:28 UTC, albig requested changes
Bitte noch mal rebasen @hbrunn , damit die Tests durchlaufen.

* show hours with float_time widget: funktioniert
* make numbers links: das klappt nicht korrekt. Es werden nur die "Ausgleichstage" verlinkt, nicht die Overtime-Zahl. Hat der Employee keine Ausgleichstage, gibt es auch keinen Link.
* 
![2023-08-02_10-27_1](https://github.com/verdigado/odoo-customize/assets/3354500/b9036c85-0331-4c6f-ba9d-2db2334dd3ad)

![2023-08-02_10-27](https://github.com/verdigado/odoo-customize/assets/3354500/82ac1a9e-5a7a-4438-b192-bd5b70913b43)

2023-08-02 10:04 UTC, hbrunn commented
@hbrunn rebase erledigt, die Links muss ich mir dann am Montag anschauen

2023-08-07 11:27 UTC, hbrunn commented
@albig ich habe das jetzt so angepasst, dass Du per Urlaubstyp definieren kannst welche Aktion gelinked wird (Feld leer=kein Link), und Ausgleichstage + Überstunden bekommen gleich die Anwesenheits-Aktion gesetzt:

![image](https://github.com/verdigado/odoo-customize/assets/2563186/516d9b16-6d43-4bb3-96e9-e041afb835d7)

Damit können dann auch beliebige andere Aktionen auf anderen Urlaubstypen gelinked werden.

Da die Urlaubstypen als noupdate definiert sind, kommt das (=den Wert dieser Felder setzen) mit einem normalen Update nicht mit, hier muss ich entweder ein Migrationsscript schreiben, Du setzt das von Hand auf bestehenden Systemen, oder sagst nicht `-u verdigado_attendance` sondern `-i verdigado_attendance`, das überschreibt auch noupdate-Daten.

Migrationsscripte sind bei parallelen Entwicklungen immer etwas problematisch, weil das die Versionsnummer des Moduls erhöhen muss, und wenn zwei PRs die Version auf `15.0.1.0.1` setzen (haben wir ja schon in #6) gibt es Konflikte.

2023-08-07 11:28 UTC, hbrunn commented on verdigado_attendance/models/hr_leave_type.py
> +                # TODO: this also applies to half days, do something?
soll ich halbe Tage zu Stunden konvertieren und auch als Stunden anzeigen, oder belassen wir es da bei dem float-Wert?

2023-08-07 14:19 UTC, hbrunn commented on verdigado_attendance/models/hr_leave_type.py
> +                # TODO: this also applies to half days, do something?
@albig TODO wie besprochen entfernt, halbe tage werden als float angezeigt

2023-08-08 09:26 UTC, albig approved these changes

2023-08-08 09:26 UTC, merged