[FIX] remove resource leaves when resetting to draft
verdigado/odoo-customize pull request #84
Opened 2023-12-18 06:54 UTC by hbrunn

2023-12-18 08:58 UTC, albig requested changes
Funktioniert leider nicht. Jetzt kann der zukünftige Urlaub nicht mehr "abgelehnt" und "als Entwurf markiert" werden.

Fehlt da wieder ein `sudo()`?

![2023-12-18_09-53](https://github.com/verdigado/odoo-customize/assets/3354500/e6d3175c-7657-4355-a422-774b962a7984)

2023-12-18 09:36 UTC, hbrunn commented
ja, danke

2023-12-18 10:12 UTC, albig commented
Das geht leider trotzdem nicht. Man muss ja erst auf "Auf Entwurf setzen" klicken und erhält dann folgendes:

![2023-12-18_11-07](https://github.com/verdigado/odoo-customize/assets/3354500/abc4a9c7-7388-4b98-b43a-300a8f3a2128)

Auf "Ablehnen" kann man ja als normaler Mitarbeiter ohnehin nicht klicken.

Man könnte den Eintrag in `resource_calendar_leaves` beim Löschen entfernen. Ich meine, das geht. Aber das löst leider nicht das Problem, dass dann ein falscher Eintrag stehen bleibt, wenn der Urlaubs-Antrag einfach geändert und wieder bestätigt wird :-(

2023-12-18 10:15 UTC, hbrunn commented
ich schreibe gerade Tests fur die Falle und verdigado_employee, _officer, _manager, das wird uns diese lästigen regressions ersparen

2023-12-18 12:42 UTC, hbrunn commented on verdigado_attendance/tests/test_holidays.py
> +    def test_standard_flow_past(self):
die Falle sind noch nicht vollständig, hier braucht es noch die ganzen Corner cases, Urlaub über Wochenenden, Feiertage, beides - hier bin ich auch etwas von Deinem Input abhängig

2023-12-19 15:22 UTC, albig approved these changes

2023-12-19 15:22 UTC, merged